LizardByte/build-deps

.github/workflows/build-ffmpeg.yml
1) Disable autodetect and iconv to reduce library conflicts from prebuilts
2) Pin build to Ubuntu 20.04 to resolve linking of libmvec/libm and libpthread when built on 22.04 then later used on 20.04. This is due to those libraries being moved around: https://developers.redhat.com/articles/2021/12/17/why-glibc-234-removed-libpthread
N/A - progress towards ffmpeg5 upgrade
=> Disable autodetect, pin to ubuntu 20

.github/workflows/build-ffmpeg.yml, ffmpeg_patches/ffmpeg/03-amfenc-disable-buffering.patch
This resolves the issue in which the last captured frame is delayed by 1ms, which
is especially noticeable in low framerate content (such as desktop streaming)
on the amfenc encoder.
Fixes all reports related to delay with callback capture using the amfenc encoder:
* https://github.com/LizardByte/Sunshine/issues/122
* https://github.com/LizardByte/Sunshine/issues/387
* https://github.com/LizardByte/Sunshine/issues/412
N.B. nvenc also experiences delay that is reported in some of the above issues. For those cases, it is resolved via a separate PR: https://github.com/LizardByte/Sunshine/pull/507
=> ffmpeg_patches: add amfenc delay/buffering fix

.github/workflows/build-ffmpeg.yml
Adds support for ARM on macOS. Note: neon has been disabled for FFmpeg which will likely make x265 (even more) unusable for this processor, but VideoToolbox hw encode should always be available.
N/A - prereq for sunshine mac arm support
=> macOS aarch64

.github/workflows/build-ffmpeg.yml
Disable AV1 decoder to reduce build time, it is unused. See https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/CMakeLists.txt#L149
=> Disable AV1 decoder build

.github/workflows/build-ffmpeg.yml
- create a pr against sunshine
- This will update all ffmpeg submodules in a single PR, whereas dependabot creates a PR for every submodule branch, which generates a ton of workflow runs for Sunshine. This PR aims to reduce the workflow runs. Additionally it will be much faster to merge the changes into Sunshine as checks will only need to pass on a single PR instead of multiple.
📝 This depends on a fork of an action to enable PRs against another repository. Once this PR is merged, the workflow can be changed back to the original maintainer. https://github.com/repo-sync/pull-request/pull/69
Todo:
[Allow edits from …
=> create pr against sunshine

.github/workflows/build-ffmpeg.yml
PR was failing to be created due to issue with `git_diff` output being multiple lines
=> fix create sunshine PR

.github/workflows/build-ffmpeg.yml, ffmpeg_patches/ffmpeg/04-mfenc-lowlatency.patch
Without this codec property enabled, MediaFoundation has noticeable delayed frames.
Enhancement for https://github.com/LizardByte/Sunshine/pull/681
=> ffmpeg: add low_latency encoder param for mediafoundation

.github/workflows/build-ffmpeg.yml, .gitmodules
Adds support for quick sync video using libmfx/mediasdk. I don't think we want to link this one statically because:
1) MediaSDK can't be built for Windows without Visual Studio
2) MediaSDK depends on LibVA so we'd also have to start building that - I'd rather not have to hassle with potential incompatibilities across different linux distros
3) oneVPL is right around the corner and undergoing lots of current development. Allowing end users to update their own library could give upcoming improvements with minimal hassle - Intel has been releasing updated Arc drivers 1-2 times/month
- Supporting change for LizardByte/Sunshine#619
must be updated before it can be merged. You …
=> QSV encoders

.github/workflows/build-ffmpeg.yml
This PR fixes submodule naming issues when creating a PR against Sunshine. See https://github.com/LizardByte/Sunshine/pull/725 for more info.
=> fix sunshine submodule names

.github/workflows/build-ffmpeg.yml
Pin build runner os versions. Sunshine will not build on Ubuntu 20.04 for aarch64 due to ffmpeg being built on 22.04.
It's possible that macOS aarch64 would also not build on macOS < 12.
=> pin build runner os versions

.github/workflows/build-ffmpeg.yml
Move `repo-sync/pull-request` back to upstream now that https://github.com/repo-sync/pull-request/pull/69 is merged and released.
- Fixes #57 
=> Move `repo-sync/pull-request` back to upstream

.github/workflows/build-ffmpeg.yml, ffmpeg_patches/ffmpeg/05-qsv-session-leak.patch
This fixes a bug in the QSV hwdevice context that causes MFX sessions (and thus the ID3D11Device and associated resources) to be leaked every time we open an encoder session.
This can't go upstream as-is due to conflicting changes in FFmpeg master, but I plan to submit a patch upstream too.
=> ffmpeg: fix MFX session leak in QSV

.github/workflows/build-ffmpeg.yml
Use kisak mesa-stable PPA to upgrade libva-dev with support for vaSyncBuffer, allowing lower latency to be achieved on Sunshine builds targeting 22.04+.
This will produce an undefined symbol error on a vanilla 20.04 installation, but that can be worked around via a stub function in Sunshine itself.
=> Build ffmpeg with vaSyncBuffer support

.gitmodules
=> build(submodules): pin SVT-AV1 to v1.4.1 branch

.github/workflows/build-ffmpeg.yml
Add support for the H.264 Video4Linux2 Memory to Memory encoder for the aarch64 and x86_64 linux versions.
=> Add h264_v4l2m2m hardware encoder support

.github/workflows/build-ffmpeg.yml
This PR (attempts) to pin binutils to 2.40 as 2.41 has caused the ffmpeg build to fail.
https://trac.ffmpeg.org/ticket/10405
=> ci(deps): pin binutils version

.gitmodules
This is a minor correction to the `.gitmodules` file, which was missed in #136.
=> build(submodules): fix ffmpeg branch in gitmodules

.github/workflows/build-ffmpeg.yml
This PR removes `nightly` branch from pull request events. Additionally, it will now use the default Sunshine branch when checking out to prepare the PR.
=> ci: remove nightly branch

.github/workflows/build-ffmpeg.yml
This PR modifies the workflow to upload all artifacts to a single `dist` branch. This is due to how submodules are pulled, which is that they download the entire git repo instead of only the branch we specified. This results in pulling 6x as much data as necessary.
=> fix! use single dist branch

.github/workflows/build-ffmpeg.yml
It has been ~5 months since the individual branches have been used as submodules by Sunshine, time to clean up.
=> ci!: stop publishing to individual branches

.github/workflows/build-ffmpeg.yml
Update ffmpeg build names per https://github.com/LizardByte/Sunshine/pull/1970#discussion_r1444095876
:warning: This will require some updates on Sunshine's side.
@chewi FYI
=> ci!: rename ffmpeg builds

.github/workflows/build-ffmpeg.yml
=> ci(windows): unpin binutils

.github/workflows/build-ffmpeg.yml
Don't checkout deleted branches.
=> fix(ci): don't checkout legacy destination branches

.github/workflows/build-ffmpeg.yml
- update macOS runners to 12
- update ubuntu runners to 22.04
=> ci(runners): update deprecated runners

.github/workflows/build-ffmpeg.yml, ffmpeg_patches/ffmpeg/06-vaapi-customized-surface-alignment.patch
Adds a patch to FFmpeg that fixes HEVC VAAPI encoding for AMD cards on Linux and updates the CI to include the patch.
Patch pulled from: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240321170219.1487-1-Primeadvice@gmail.com/
Tested with sunshine built from [e7c420dd6ee45760d98829a311b35be7dfb118b4](https://github.com/LizardByte/Sunshine/commit/e7c420dd6ee45760d98829a311b35be7dfb118b4) and the resulting build fixes the issue mentioned below with Mesa versions newer than 24.0.4.
- Closes https://github.com/LizardByte/Sunshine/issues/2636
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collabor …
=> fix(linux): add customized surface alignment patch for VAAPI on AMD

.github/workflows/build-ffmpeg.yml, ffmpeg_patches/ffmpeg/07-amfenc-query-timeout.patch
This adds a patch to use the AMF `QUERY_OUTPUT` encoder feature to avoid busy looping while waiting for encoder output. 
According to my testing with the EncoderLatency sample in the AMF repository, this has no impact to output latency (avg/min/max encoding time in milliseconds):
- OneInOne algorithm, AMF_VIDEO_ENCODER_QUERY_TIMEOUT=0, no sleep in `AMF_REPEAT` case (equivalent to Sunshine today): 1.76/1.47/3.76
- OneInOne algorithm, AMF_VIDEO_ENCODER_QUERY_TIMEOUT=50, no sleep in `AMF_REPEAT` case (equivalent to this PR): 1.74/1.48/3.76
=> fix(amfenc): stop busy waiting for encoder output

.github/workflows/build-ffmpeg.yml, cmake/ffmpeg_cbs.cmake, cmake/toolchain/aarch64-linux/crosscompile.cmake, cmake/toolchain/aarch64-macos/crosscompile.cmake, cmake/toolchain/powerpc64le-linux/crosscompile.cmake
If you set arch-specific `CFLAGS`, then ffmpeg's configure script may fail when it tries to use these flags against the build host's compiler.
Also use `CMAKE_SYSTEM_PROCESSOR` to set up cross-compiling without relying on any custom variables. ffmpeg normalises its `--arch` option and will accept just about any string that you'll likely throw at it.
=> fix: cross-compiling and don't treat x86 as the default case

.github/workflows/build-ffmpeg.yml
This fixes the linking error for Sunshine on Darwin ARM64 that was caused by `--disable-neon`. It also uncripples the Darwin ARM64 build by enabling NEON optimizations for massive speed improvements across libswscale and other parts of FFmpeg.
=> build(ffmpeg): compile on native ARM64 builders with NEON

ffmpeg_patches/ffmpeg/05-vaapi-customized-surface-alignment.patch
We build FFmpeg with libva 2.14 since we're using Ubuntu 22.04. This means the FFmpeg patch introduced in #335 won't actually work when it's compiled using our GitHub Actions. This PR fixes that by manually defining the `VASurfaceAttribAlignmentSize` enum value that we need if the libva headers are too old.
I also restored the context in the patch that was lost when I rebased it on FFmpeg 7.1.
https://github.com/LizardByte/Sunshine/issues/2636
=> fix(vaapi): fix surface alignment when building with libva <1.21

.github/workflows/build-ffmpeg.yml, ffmpeg_patches/ffmpeg/07-avcodec-options-revert.patch
Reverts a broken commit from FFmpeg 7.1 that caused https://github.com/LizardByte/Sunshine/issues/3273
=> fix(ffmpeg): revert broken commit from FFmpeg 7.1

.github/workflows/build-ffmpeg.yml, ffmpeg_patches/ffmpeg/07-vaapi-leak.patch
These patches are necessary to address the regression reported in https://github.com/LizardByte/Sunshine/issues/3268. It is typically just a leak, but it can become a crash in cases where we call `eglTerminate()` but the leaked VAAPI surfaces keep references to the DRI driver alive. On the next attempt to use EGL, it ends up invoking functions in a module that has been unloaded.
=> fix(ffmpeg): apply upstream patches to fix VAAPI leaks and crashes

.github/workflows/build-ffmpeg.yml, ffmpeg_patches/ffmpeg/08-nvenc-av1-filler.patch
This adds a patch to allow us to opt-out of AV1 padding OBUs for CBR with NVENC. Bitstream padding is a waste of valuable network bandwidth and also causes problems with Qualcomm's (broken) AV1 decoder.
Reference: https://github.com/LizardByte/Sunshine/issues/3331
=> fix(nvenc): allow opt-out of filler data for AV1

.gitmodules
This PR moves all submodules hosted outside of GitHub to mirrors at the LizardByte-infrastructure org.
=> build(deps): move all submodules to github mirrors

cmake/apply_git_patch.cmake
Using `::error::` or `::warning::` will make the errors prominent in the workflow summaries. Although this will not fail any job.
=> build(cmake): make error prominent in GitHub CI

.github/workflows/ci.yml
This reverts commit 7b9e52ef2b377ea2d9cc6b8253850aa0e6e6fb21.
It will fix CI build fails on aarch64 and ppc64le target.
CI Fail Link: https://github.com/LizardByte/build-deps/actions/runs/14978334141/job/42076211911
After revert, all thing is OK, CI Passed Link: https://github.com/rbqvq/build-deps/actions/runs/14978879753/job/42077952271
None
None
=> revert: ci(build): fix sed replacement in ubuntu sources (#419)

.github/workflows/ci.yml, CMakeLists.txt, README.md, cmake/ffmpeg/_main.cmake, cmake/ffmpeg/ffmpeg.cmake, cmake/ffmpeg/nv_codec_headers.cmake, cmake/ffmpeg/x264.cmake, cmake/ffmpeg/x265.cmake
This PR adds a FreeBSD build of FFmpeg which will be required to complete https://github.com/LizardByte/Sunshine/pull/4049
See: https://github.com/LizardByte/roadmap/issues/90
Noteworthy changes:
- fixed issue where we could not use the recursive option of the actions/checkout GitHub action, x265 required tags to be fetched if git is installed otherwise the x265.pc file would not be installed
- fixed issue where parallel builds would always be 1 instead of using the processor count
- artifact upload will now fail if no files are found
- many FFmpeg flags are now defined by what cmake build options are enabled/disabled
- CC/CXX flags are now properly passed to x264
More notes specific to FreeBSD build:
- AMF is disabled as the build failed
- cuda, ffnvcodec, nvenc are disabled for aarch64 …
=> feat(FFmpeg): add FreeBSD build

.github/workflows/ci.yml
The aarch64 FreeBSD vm is only using 2 processors, but should use the same amount as the host provides. Additionally, some steps were re-ordered to not use the VM which will be faster for the aarch64 build.
=> ci(freebsd): use all processors for aarch64 vm
