.github/workflows/build-ffmpeg.yml

fix yamllint errors

---

.github/workflows/build-ffmpeg.yml

enable hvec_amf for linux

---

.gitmodules

update submodule branches

---

.github/workflows/build-ffmpeg.yml
ffmpeg_patches/ffmpeg/01-idr-on-amf.patch
ffmpeg_patches/ffmpeg/02-amf-color-fixes.patch

- add amf patches from original [sunshine-prebuilt](https://github.com/TheElixZammuto/sunshine-prebuilt)

add amf patches

---

.github/workflows/build-ffmpeg.yml

Make x265 build static to avoid link issues

Static x265 build

---

.gitmodules

use ffmpeg github mirrors

---

.github/workflows/build-ffmpeg.yml
.gitmodules

- add ffmpeg av1 encoder using SVT-AV1

add ffmpeg av1 encoder

---

.github/workflows/build-ffmpeg.yml

- remove sudo from nvenc make install

fix nvenc make install

---

CMakeLists.txt
cmake/apply_git_patch.cmake
cmake/ffmpeg_cbs.cmake

fix cmake-lint errors

---

.github/workflows/build-ffmpeg.yml

update workflow concurrency to prevent multiple runs in the same PR

update workflow concurrency

---

.github/workflows/build-ffmpeg.yml

Add QSV on Linux

---

.github/workflows/build-ffmpeg.yml

`pkg-config` seems to have been removed from GitHub runners, so re-adding it.

build(deps): add pkg-config for macOS build

---

.gitmodules

- x265_git pinned to `Release_3.5` branch
- AMF pinned to `bc64bf6e8bfca3083755b7cbec3c23d5546fb04a` (v1.4.29)
- SVT-AV1 pinned to `018276d714ce65d9b586f6205ee016cbd8d5425d` (v1.4.1)

deps: pin submodules

---

.github/workflows/build-ffmpeg.yml
cmake/ffmpeg_cbs.cmake
cmake/toolchain/powerpc64le-linux/crosscompile.cmake
ffmpeg_patches/cbs/02-include-cbs-config.patch

Add Linux powerpc64le architecture for ffmpeg build.

build(ffmpeg): add powerpc64le architecture

---

.gitmodules

Pin SVT-AV1 to v1.6.0 branch.
Replaces #170 

build(submodules): pin SVT-AV1 to v1.6.0 branch

---

.gitmodules

Update to the formal release of FFmpeg 6.1 and retarget branch updates to `release/6.1`.

Update to FFmpeg 6.1

---

.github/workflows/build-ffmpeg.yml

ppc64el build broken due to sub dependencies missing.

fix(build): fix ppc64el dependencies

---

.github/workflows/build-ffmpeg.yml

If https://github.com/LizardByte/Sunshine/pull/2323 is to be merged, its statically built dependencies need to be binary-compatible with UCRT sunshine. So, do.

Build ffmpeg for windows using Universal CRT runtime.

---

.github/workflows/build-ffmpeg.yml

Unneeded files are still in dist branch.

ci: cleanup dist share and pkgconfig directories

---

LICENSE
README.md

Add a simple readme and license (MIT).

docs: add readme and license

---

.github/workflows/ci.yml

By using `aptitude` to install apt packages, we can avoid the issues that apt has resolving dependencies for architecture specific packages.

ci(cross-compile): use aptitude to install apt packages

---

.github/workflows/ci.yml

Cross compiled architectures on Ubuntu are now failing to install dependencies. Something probably changed in the sources files.

ci(build): fix sed replacement in ubuntu sources

---

cmake/ffmpeg/mf.cmake
cmake/ffmpeg/x264.cmake
cmake/ffmpeg/x265.cmake

Wrong reference, maybe you forgot to change it when you copied it?
None
None

fix(patch): fix apply patches

---

.github/workflows/ci.yml

Stop gap until https://github.com/LizardByte/build-deps/pull/415 is ready.

build(ci/windows): pin cmake to v3.31 and gcc to v14.2

---

.gitmodules

chore(deps): bump x265

---

.gitmodules

Stable branch has not been updated in 2+ years.
This change does not actually change the commit, but dependabot should start watching the master branch instead of stable.

chore(deps): move x264 to master branch

---

.github/workflows/ci.yml
cmake/boost/_main.cmake

This PR enables boost for ppc64le architecture.

fix(boost): allow compile on ppc64le
